CXX=gcc
CFLAGS=-lraylib

window :
	$(CXX) $(CFLAGS) window.c -o window.out

ball :
	$(CXX) $(CFLAGS) ball.c -o ball.out

ballcolor:
	$(CXX) $(CFLAGS) ballcolor.c -o ballcolor.out

cubescroll:
	$(CXX) $(CFLAGS) cubescroll.c -o cubescroll.out

camera:
	$(CXX) $(CFLAGS) camera.c -o camera.out

drawpoly:
	$(CXX) $(CFLAGS) drawpoly.c -o drawpoly.out

clean :
	rm *.out
